### ISSUE TITLE
Update user "cart" to allow a greater number samples

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#192]
Based on the way the current cart system functions, when users add a large number of samples to the cart the interface becomes sluggish.

**TODOs**

* [x]  UI:
  * [x] Remove client side code for slide out cart
  * [x] Cart Page
* [x] Server:
  * [x] Add samples to cart
  * [x] Remove samples from cart
  * [x] Remove project from cart
* [x]  Fix Tests:
  * [x] CartControllerTest
  * [x] PipelinesPhylogenomicsPageIT
  * [x] AssemblyPipelinePageIT
  * [x] CartControllerIT

**Comment by tom114** [comment]
Fixes #68
