### ISSUE TITLE
Update SISTR in IRIDA

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#196]
# Additions for SISTR

Most of these have been incorporated into the latest SISTR release [SISTR v1.1.1](https://github.com/phac-nml/sistr_cmd/releases).

* [x] Update SISTR database.
* [x] Update to say `loci found` in addition to `alleles found` (https://github.com/peterk87/sistr_cmd/issues/23)
* ~[ ] Mash output should give closest genome, not just closest salmonella~ - Will not implement here
* [ ] QC warning if < 10 representatives in SISTR database for a serovar (https://github.com/peterk87/sistr_cmd/issues/24)
   * _Note: I believe this is also taken into account by the **Reportable serovars** column in [irida-sistr-results](https://github.com/phac-nml/irida-sistr-results#reportable-serovar-status-column) but I'd have to double-check._

# Integrate SISTR into IRIDA

* [x] Update [SISTR tool in Galaxy](https://github.com/phac-nml/galaxy_tools/blob/e795229a49483da24e80fab0809216557de09840/tools/sistr_cmd/sistr_cmd.xml) to version `1.1.1` (latest release).
* [x] Incorporate newest version of the IRIDA/SISTR pipeline (pipeline files [here](https://github.com/phac-nml/irida/tree/development/src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SISTRTyping/0.3)) - [Edit: this will be done as a plugin]
    * [x] Update version of the Shovill genome assembler in the workflow from `0.9.0` to the latest version in Galaxy `1.1.0+galaxy0` ([Shovill Galaxy tool](https://toolshed.g2.bx.psu.edu/view/iuc/shovill/83ead2be47b2)).
    * [x] Update Shovill parameters to better defaults (e.g., contig threshold to 1). See https://github.com/phac-nml/irida/issues/185.
    * [x] Update [SISTR Sample Updater](https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/SISTRSampleUpdater.java) to incorporate new SISTR result fields into the metadata table. A screenshot of the metadata table can be found [here](https://raw.githubusercontent.com/phac-nml/irida/development/doc/user/user/sample-metadata/images/linelist_base.png).
* [ ] Update SISTR results in IRIDA UI.
    * [ ] Update SISTR results page (in particular to show additional information such as **loci found** in addition to **alleles found**). An example of what this page looks like is [here](https://raw.githubusercontent.com/phac-nml/irida/development/doc/user/user/sistr/images/sistr-results.png).
    * The main source file is [here](https://github.com/phac-nml/irida/blob/development/src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx) but here may be other files to update to get it working.
* [ ] Update the SISTR pipeline documentation in IRIDA with any new changes (e.g., description of output files or screenshots).
    * [ ] Update [SISTR tutorial](https://github.com/phac-nml/irida/blob/development/doc/user/tutorials/sistr/index.md) (may only need to update some screenshots and a bit of text).
    * [ ] Update [pipeline description](https://github.com/phac-nml/irida/blob/development/doc/user/user/sistr/index.md).
    * [ ] Update [install instructions](https://github.com/phac-nml/irida/blob/development/doc/administrator/galaxy/pipelines/sistr/index.md) (mostly need to update the Galaxy tool versions).
* ~[ ] Update IRIDA Galaxy Docker with latest tools. This is better left for the update SNVPhyl issue since I have to update the Docker image there too (and I was already working on it).~ Will be solved in #713
* [ ] Test updated SISTR pipeline to make sure it returns the correct results for some datasets (I'm not sure which dataset to use or how necessary since I'm not sure if people have already tested the SISTR command-line application).

# Additional tasks

* [ ] Update the `irida-sistr-results` command-line tool to include new fields produced by SISTR https://github.com/phac-nml/irida-sistr-results/issues/13. This task can be done independently of an IRIDA release. It also depends on if people still use this program to extract SISTR results (or if they used the metadata/linelist table).

**Comment by kbessonov1984** [comment]
Current updates as of today Aug 12:
* The objective `Update SISTR tool in Galaxy to version 1.1.1 (latest release)` is complete. Galaxy has now the newest version of `SISTR v1.1.1`
* `Incorporate newest version of the IRIDA/SISTR pipeline` is complete. I need to push new code to the PHAC repository.
    *  Galaxy Project workflow updates with 
       *`Minimum contig length` set to 1 bp in `shovill` parameters
       * Shovill updated to version `1.1.0+galaxy0`
      * `SISTR Sample Updater` in now outputs new fields in the IRIDA project metadata
TODO: provide link to new IRIDA SISTR workflow

**Comment by tom114** [comment]
Now that SISTR has been externalized into a plugin at https://github.com/phac-nml/irida-plugin-sistr, we're targeting to remove the built-in SISTR from IRIDA.  This will be tracked in a new issue at https://github.com/phac-nml/irida/issues/1022.
